spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  datasource:
    url: "jdbc:mysql://localhost:3306/paperdelivery?serverTimezone=UTC&useLegacyDatetimeCode=false"
    username: root
    password: uIMvGp:QU6Mm
    validation-query: SELECT 1;

management:
  endpoints:
    web:
      base-path: /manage


